default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# Development database configuration
development:
  <<: *default
  database: events_development

# Test database configuration
test:
  <<: *default
  database: events_test

# Production database configuration (Using Scalingo's DATABASE_URL)
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
